Feature/home page
MegaK-group-1/head-hunter-frontend pull request #3
Opened 2022-07-19 15:31 UTC by PatrykKeska

2022-07-19 16:44 UTC, joanbier reviewed
Jak dla mnie wygląda wszystko ok, chociaż nie ogarniam tej biblioteki Atom, niech się inni wypowiedzą ;D

2022-07-19 17:09 UTC, joanbier commented on src/Atoms/Input/Input.tsx
> +export const Input = styled.input`
możemy tutaj zmienić width na jednostkę względną np. vw. Będzie wtedy bardziej RWD i ładnie się skalowało na netbooka czy większego tableta, lub odpowienio duże na większych monitorach typu 28cal. W AdobeXD mockup mamy ustawione na 1920 × 1080, łatwo obliczyć proporcję. W typ przypadku width możemy zapisać jako 18vw.

2022-07-19 17:10 UTC, joanbier commented on src/Atoms/LogoMegaK/LogoMegaK.tsx
> +  width: 124px;
tutaj można zastosować podobnie jak z inputem, wpisać w  % lub vw

2022-07-19 17:11 UTC, joanbier commented on src/Atoms/LogoMegaK/LogoMegaK.tsx
> +  height: 76px;
heigh wtedy na auto, bedzie się automatycznie saklować

2022-07-19 17:15 UTC, joanbier commented on src/Atoms/Wrapper/Wrapper.tsx
> +export const Wrapper = styled.div`
Trzeba się pozbyć scrollbarów pionowych i poziomych. Zamiast min-height zastosować max-height lub overflow hidden

2022-07-19 17:23 UTC, joanbier commented
Co do mobile, dobrze zrobić media na 768px i dać np inputy na 90vw etc.

2022-07-19 17:36 UTC, joanbier commented
Dopatrzyłam się jeszcze, że brakuje font-family 'Catarman' oraz odpowiedni font-size jak w mockupie

2022-07-19 19:16 UTC, joanbier approved these changes

2022-07-19 20:19 UTC, zannien94 requested changes

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/Input/Input.tsx
> +import styled from "styled-components";
jezeli robisz plik Input to po co folder jezeli nic wiecej niema ? 
jezeli juz tworzymy folder dla Input to fajnie by bylo zrobic plik do exportu np. index.js wtedy unikamy importu Input/Input -https://github.com/airbnb/javascript

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/LoginButton/LoginButton.tsx
> +import React from "react";
to samo co powyzej

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/LoginButton/LoginButton.tsx
> +        <Button>Zaloguj Się</Button>
jak myslisz Button bedzie chyba uzywany w nie jednym miejscu ? 
moze warto by bylo zrobic kompontent Button i przekazac do niego propsa ? text ?

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/LogoMegaK/LogoMegaK.tsx
> +import styled from "styled-components";
to samo co powyzej

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/Paragraph/Paragraph.tsx
> +import styled from "styled-components";
to samo co powyzej

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/StyledLink/Link.tsx
> +import styled from "styled-components";
to samo co powyzej

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/StyledLink/Link.tsx
> +
jezeli uzywamy 2x props moze warto zrobic jeden wrapper ? 
${({ align, underline }) => css`
  color: white;
  align-self:${align} ;
  text-decoration: ${underline || "none"};
`}

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/StyledLink/Link.tsx
> +export const StyledLink = (props:Props)=>{
fajnie by bylo zdestrukturyzowac propsy

2022-07-19 20:19 UTC, zannien94 commented on src/Atoms/Wrapper/Wrapper.tsx
> +import styled from "styled-components";
to samo co powyzej , ogolnie zerknij na wiekszosc plikow

2022-07-19 20:19 UTC, zannien94 commented on src/Molecules/LoginForm/LoginForm.tsx
> +import React from "react";
importy absolutne powinny raczej byc przy importach absolutnych 

import absolute
import relative 

czyli pierw importy z node modules a potem swoje komponenty

2022-07-19 20:19 UTC, zannien94 commented on src/Molecules/LoginForm/LoginForm.tsx
> +                type={"email"}
wywal { - brackety nic tutaj nie wnosza

2022-07-19 20:19 UTC, zannien94 commented on src/index.tsx
> +import {BrowserRouter} from "react-router-dom";
prosze wynies na poczatek pilku

2022-07-20 05:46 UTC, oohajo approved these changes

2022-07-20 06:27 UTC, PatrykKeska commented on src/Atoms/Input/Input.tsx
> +import styled from "styled-components";
Wprowadziłem te zmiany o których pisałaś, zostawiłem folder przy formularzu logowania z racji że na pewno będą jakieś funkcje dodane

2022-07-20 07:41 UTC, zannien94 approved these changes

2022-07-20 10:37 UTC, PatrykKeska commented
Jężeli nie ma wiekszych/mniejszych problemów to leci marge do developa, z racji że już powstałe komponenty będą re używalne w następnych widokach

2022-07-20 10:40 UTC, merged